apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 4sh-formation-@ME
resources:
  - ../../base
configMapGenerator:
  - name: env-config
    envs:
      - env.conf
  - name: app-config
    files:
      - app.conf
